export const FETCH_CITIES_LIST = "FETCH_CITIES_LIST";
export const FETCH_LEFT_WEATHER = "FETCH_LEFT_WEATHER";
export const FETCH_RIGHT_WEATHER = "FETCH_RIGHT_WEATHER";
export const CHANGE_LANG = "CHANGE_LANG";
